apiVersion: v1
data:
  local.config.yml: |+
server:
{{- if .Values.pygeoapi.config.server }}
{{- toYaml .Values.pygeoapi.config.server | nindent 2 -}}
{{- end }}
logging:
{{- if .Values.pygeoapi.config.logging }}
{{- toYaml .Values.pygeoapi.config.logging | nindent 2 -}}
{{- end }}
metadata:
{{- if .Values.pygeoapi.config.metadata }}
{{- toYaml .Values.pygeoapi.config.metadata | nindent 2 -}}
{{- end }}
resources:
{{- if .Values.pygeoapi.config.resources }}
{{- toYaml .Values.pygeoapi.config.resources | nindent 2 -}}
{{- end }}

kind: ConfigMap
metadata:
  name: {{ .Values.pygeoapi.configmap_name }}
  namespace: {{ .Values.global.namespace }}
