apiVersion: v1
data:
  pycsw.yml: |+
{{- if .Values.pycsw.config }}
  {{- toYaml .Values.pycsw.config | nindent 4 -}}
{{- end }}

kind: ConfigMap
metadata:
  name: {{ .Values.pycsw.configmap_name }}
  namespace: {{ .Values.global.namespace }}
