nameOverride: ""
fullnameOverride: ""
kubeVersionOverride: ""
deployment:
  replicaCount: 1
  image:
    pullPolicy: IfNotPresent
  strategy:
    type: Recreate
    # rollingUpdate:
    #   maxSurge: 25%
    #   maxUnavailable: 25%
  automountServiceAccountToken: false
  podAnnotations: {}
  podLabels: {}
  podSecurityContext:
    enabled: false
    # fsGroup: 2000
  containerSecurityContext:
    enabled: true
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    # runAsUser: 1000
  extraArgs: []
  # - --foo
  # - --bar
  extraEnvVars: []
  # - name: FOO
  #   value: BAR
  extraVolumes: []
  # - emptyDir: {}
  #   name: tmp
  extraVolumeMounts: []
  # - mountPath: /tmp
  #   name: tmp
  priorityClassName: ""
  hostAliases: []
  # - ip: "127.0.0.1"
  #   hostnames:
  #   - "foo.local"
  #   - "bar.local"
  # - ip: "10.1.2.3"
  #   hostnames:
  #   - "foo.remote"
  #   - "bar.remote"
  resources:
    limits: {}
    #   cpu: 100m
    #   memory: 128Mi
    requests: {}
    #   cpu: 100m
    #   memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  livenessProbe:
    enabled: false
    httpGet:
      path: /oauth/health
      port: admin
  readinessProbe:
    enabled: true
    httpGet:
      path: /oauth/health
      port: admin
service:
  type: ClusterIP
  annotations: {}
  proxy:
    port: 3000
    nodePort:
  admin:
    port: 4000
    nodePort:
serviceAccount:
  create: true
  annotations: {}
  name: ""
ingress:
  enabled: true
  className: ""
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: identity.api-gatekeeper.develop.eoepca.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: identity-gatekeeper-tls-certificate
      hosts:
        - identity.gatekeeper.develop.eoepca.org
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  #targetMemoryUtilizationPercentage: 80
pdb:
  create: false
  minAvailable: 1
metrics:
  addPrometheusScrapeAnnotation: false
  serviceMonitor:
    enabled: false
    namespace: um
    additionalLabels: {}
    annotations: {}
    interval:
config:
  client-id: identity-api
  discovery-url: https://identity.keycloak.develop.eoepca.org/realms/master
  no-redirects: true
  no-proxy: true
  secure-cookie: true
  enable-default-deny: true
  enable-uma: true
  enable-metrics: true
  enable-logging: true
  enable-request-id: true
  enable-login-handler: true
  enable-refresh-tokens: true
  enable-logout-redirect: true
  listen: :3000
  listen-admin: :4000
secrets:
  clientSecret: AgB5Ti7IRPPnKsz33D/H+7SbURa1VffHyRFz4/osU3+1sGk1NvwqFp1sAAwummf70hCcFkTEaCKIaTtAmNidy/kEaaKPLb9LoxHx+D6A0xs8Z4KxnrTwUKbw5s5MtVosqqQVvni8nCRMA77h3N1rLRLAVRavhpei6OZO8780Asv+oMvaZ5WjV5XZWkZij2rAxDNU/L8uGyGI6zyxv08oJgT/RS0T3XA7F8eaaAe7PCBq9L5aep8mXX6sNL8fJPQmHb+aICLkUPB8fa5tybhXd6M7pPd4ppr6TUwZnm8Vd5fakmKPHbr5WMZfSsGPtOQ1mWF1ct/ny9CY58X3jUzV/rXft5l9onZsOgzblF2bSPLcnxnqsU7cqwgdkr2475JlOzm1GlU4PLMQU3XdB9BfbhqRdPrTGqj4HFCtp3TTDYP3ZwFI1wKk80VdolQRxeMkfRJB8W78bncih9bM4r7WFbM12I1DNPCAL75z14h6Wt3R3rOljPtUPCMeTl5qys+AQuDRYVH0m4QoOYk3HkEN9AIV70oePRgV1tZNht4Tk6Qo+bEe38tUTZXT1nTVroK56vz0xFpOgJCyGBMx5Ni/GtWeKM2JJUmcNimAxvx0PBeVAO/zyOirco0Ifanr6EeIW2yAPrmqaAUBu81qp8g7tHxwEErTGDQmRifOPNu5xpJP4oZPl8tPp7EPwz4i0ckrivo/Fufr5UcJjgAgctUKV+OKC0fm3+9l8VXBXkjuKs8tGA==
  encryptionKey: AgBR5OuVEA1Dxn/VJWG/s7lXNM0KuO+MqZgEmn5WTfSQsMxQfUJHIaqnNMq14gcqDYgW7rzP9HFUFX9A/4sOSYwhlV/SqA+fgpww3MJbGG0kYYxcJKuwUCOkGCNC0zFzu7RUs1qGpxQ/MCw/uzOdjtoDbg1/RvCiRK/6f/gtXDopoBzFjjQ2dT/Y0/+jasni0/dbaEFA9U4YPOEo9UO6H7BQez1RREff7+FPQjroX/49uUqw5IOAzYjNPQ9IVz1NSvLhpeVnB1WcVhIxnMZ60D+DScD8XOK14xS0namx0aV7tcSKqj4sOx6kBbcyUJ648rWfxLikU1m7pTcB8VAfpL4BnMFtkzeIK/PC4FEpaNFN5CgV7xbBE4p5HwqbjpBkpn+tlyZf8Yfo8PrehKS091z99AsbmCe3Hi+Nw1kmYI2iNYKC5WxjfifDsRtvnJMcB/o5pw7ZdaHgnNr2f3xai8KmpIwziEnmtvYnOvuUp4EluRJwOtSc2WS+dLSlJfbm2TDjr0goLqM8zAG0S7tBnoAc1DWd3unOQ689fQ/GFkYtO2o0P2es1RB2b3p5HYaWT532rQvahVj2Rdg47rxUBF691O+TEHG3k1NML5Tynp7fjSNXyy5SajW1yO+nFy96zEUI0IFI6CmBzhMfwmRde13utLakBe8ctXozB5D3MonPdT5T8KCdTfswqa3ymxaIBx8=