{{- if .Values.installCRDs -}}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sources.package.r
  labels:
    {{- include "workspace-ui.labels" . | nindent 4 }}
spec:
  conversion:
    strategy: None
  group: package.r
  names:
    kind: Source
    listKind: SourceList
    plural: sources
    singular: source
  scope: Namespaced
  versions:
  - name: alphav1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
{{- end }}