apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "workspace-ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    verbs: ["get", "list", "watch", "patch", "create", "delete"]
    resources:
      - secrets
  - apiGroups: ["package.r"]
    verbs: ["get", "list", "watch", "patch", "create", "delete"]
    resources:
      - sources
