apiVersion: package.r/alphav1
kind: Source
metadata:
  name: {{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.s3CredentialsSecretName }}
spec:
  access:
    secretName: {{ .Values.s3CredentialsSecretName }}
{{- end }}
