format: 'sarif'
output: 'trivy-scan.sarif'
severity: 'CRITICAL,HIGH,MEDIUM,UNKNOWN'
exit-code: 0
helm:
  scanners:
    - helm
    - kubernetes
scan:
  skip-dirs:
    - billing-service
    - cheese
    - django-portal
    - dummy
    - eoapi-maps-plugin
    - identity-gatekeeper
    - identity-service
    - license-manager
    - login-service
    - nfs-provisioner
    - pde-jupyterhub
    - pdp-engine
    - pep-engine
    - pricing-engine
    - resource-guard
    - rm-bucket-operator
    - rm-bucket-operator-wrapper
    - rm-minio-bucket-api
    - rm-registration-api
    - rm-user-workspace
    - storage
    - uma-user-agent
    - user-profile
