apiVersion: v1
kind: Service
metadata:
  name: {{ include "identity-portal.name" . }}
  labels:
    {{- include "identity-portal.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "identity-portal.selectorLabels" . | nindent 4 }}