apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: jupyterhub
deploy:
  helm:
    releases:
      - name: jupyterhub
        chartPath: .
        namespace: default
        valuesFiles:
          - values.yaml
