service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  ingressClassName:
  hosts: []
  pathSuffix:
  pathType: Prefix
  tls: []
  clusterIssuer: "letsencrypt"

nodeSelector:
  key: node-role.kubernetes.io/worker
  value: \"true\"

jupyterhub:
  # fullnameOverride and nameOverride distinguishes blank strings, null values,
  # and non-blank strings. For more details, see the configuration reference.
  fullnameOverride: "application-hub"
  nameOverride:

  # imagePullSecrets is configuration to reference the k8s Secret resources the
  # Helm chart's pods can get credentials from to pull their images.
  imagePullSecrets: []

  # hub relates to the hub pod, responsible for running JupyterHub, its configured
  # Authenticator class KubeSpawner, and its configured Proxy class
  # ConfigurableHTTPProxy. KubeSpawner creates the user pods, and
  # ConfigurableHTTPProxy speaks with the actual ConfigurableHTTPProxy server in
  # the proxy pod.
  hub:
    serviceAccount:
      create: true
      name: ""
    networkPolicy:
      enabled: false
    db:
      type: sqlite-pvc
      upgrade:
      pvc:
        annotations: {}
        selector: {}
        accessModes:
        - ReadWriteOnce
        storage: 1Gi
        subPath:
        storageClassName: standard
    args:
    - "jupyterhub"
    - "--config"
    - "/usr/local/etc/applicationhub/jupyter_config.py"
    - "--debug"
    - "--upgrade-db"
    extraEnv:
      JUPYTERHUB_AUTH_METHOD: dummy
      JUPYTERHUB_ENV: dev
      JUPYTERHUB_FULLNAME_OVERRIDE: "application-hub"
      JUPYTERHUB_SINGLE_USER_IMAGE_NOTEBOOKS: "jupyter/minimal-notebook:2343e33dec46"
      STORAGE_CLASS: standard
      RESOURCE_MANAGER_WORKSPACE_PREFIX: "develop-user"
    extraVolumes:
    - name: application-hub-config
      configMap:
        name: application-hub-jupyter-config
        standardMode: 0744
    extraVolumeMounts:
    - name: application-hub-config
      mountPath: /usr/local/etc/applicationhub
    image:
      name: eoepca/application-hub
      tag: "1.4.3"
      pullPolicy: IfNotPresent


  # proxy relates to the proxy pod, the proxy-public service, and the autohttps
  # pod and proxy-http service.
  proxy:
    secretToken: ""
    chp:
      networkPolicy:
        enabled: false
    service:
      type: ClusterIP #LoadBalancer
    # traefik relates to the autohttps pod, which is responsible for TLS
    # termination when proxy.https.type=letsencrypt.
    traefik:
      image:
        name: traefik
        # tag is automatically bumped to new patch versions by the
        # watch-dependencies.yaml workflow.
        #
        tag: "v3.2.1" # ref: https://hub.docker.com/_/traefik?tab=tags

  # singleuser relates to the configuration of KubeSpawner which runs in the hub
  # pod, and its spawning of user pods such as jupyter-myusername.
  singleuser:
    networkPolicy:
      enabled: false
      egressAllowRules:
        cloudMetadataServer: false
