apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "identity-gatekeeper.name" . }}
  labels:
    {{- include "identity-gatekeeper.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    POSTGRES_PASSWORD: "{{ .Values.secrets.postgresPassword }}"
    PGPASSWORD: "{{ .Values.secrets.pgPassword }}"