
#{{- $authRptCookieName := (printf "%s-%s" .Values.authRptCookieName .Values.global.context) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: test
  name: identity-dummy-service
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/configuration-snippet: |
      #---
      # establish the auth request endpoint
      #---
      auth_request /authcheck;
      # Unpick the auth_request response
      auth_request_set $x_user_id $upstream_http_x_user_id;
      auth_request_set $x_auth_rpt $upstream_http_x_auth_rpt;
      auth_request_set $x_auth_rpt_options $upstream_http_x_auth_rpt_options;
      # Set headers on the proxied request
      proxy_set_header X-User-Id $x_user_id;
      proxy_set_header Authorization "Bearer $x_user_id";
      # Set headers in the response
      add_header Set-Cookie "auth_rpt=$x_auth_rpt;$x_auth_rpt_options";
    nginx.ingress.kubernetes.io/server-snippet: |
      location ^~ /authcheck {
        internal;
        proxy_pass https://identity.gatekeeper.develop.eoepca.org/;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Original-URI $request_uri;
        proxy_set_header X-Original-Method $request_method;
      }
spec:
  ingressClassName: nginx
  rules:
    - host: identity.dummy-service.develop.eoepca.org
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: dummy-service
                port:
                  number: 80
  tls:
    - hosts:
        - identity.dummy-service.develop.eoepca.org
      secretName: identity-dummy-service-tls