identity-postgres:
    enabled: true
    deployment:
        image:
            repository: postgres
            pullPolicy: IfNotPresent
identity-keycloak:
    enabled: true
    deployment:
        image:
            repository: quay.io/keycloak/keycloak
            pullPolicy: IfNotPresent
identity-identity-api:
    enabled: true
    deployment:
        image:
            repository: ghcr.io/eoepca/um-identity-api
            pullPolicy: IfNotPresent
identity-manager:
    enabled: true
    deployment:
        image:
            repository: ghcr.io/eoepca/um-identity-manager
            pullPolicy: IfNotPresent
identity-proxy:
    enabled: true
    deployment:
        image:
            repository: quay.io/oauth2-proxy/oauth2-proxy
            pullPolicy: IfNotPresent