apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-portal-keycloak.name" . }}
  labels:
    {{- include "django-portal-keycloak.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    name: http
    targetPort: 8080
    protocol: TCP
  selector:
    app: portal