{{ if .Values.iam.keycloak.configuration.useCrossplane -}}
{{ if .Values.iam.keycloak.configuration.createClients -}}
{{ if .Values.iam.opa.enabled -}}
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: opa-client
spec:
  deletionPolicy: Delete
  forProvider:
    accessType: confidential
    clientId: opa
    clientSecretSecretRef:
      key: client_secret
      name: opa-route
      namespace: {{ .Release.Namespace }}
    realmIdRef:
      name: eoepca-realm
    serviceAccountsEnabled: true
  providerConfigRef:
    name: keycloak-provider-config
{{- end }}
{{- end }}
{{- end }}