{{ if .Values.iam.keycloak.configuration.useCrossplane -}}
{{ if .Values.iam.keycloak.configuration.createClients -}}
{{ if .Values.iam.identityApi.enabled -}}
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: identity-api-client
spec:
  deletionPolicy: Delete
  forProvider:
    accessType: confidential
    clientId: identity-api
    clientSecretSecretRef:
      key: client_secret
      name: identity-api-route
      namespace: {{ .Release.Namespace }}
    realmIdRef:
      name: eoepca-realm
    serviceAccountsEnabled: true
  providerConfigRef:
    name: keycloak-provider-config
{{- end }}
{{- end }}
{{- end }}