{{ if .Values.iam.keycloak.configuration.useKeycloakConfigCli -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: initial-keycloak-config
  namespace: {{ .Release.Namespace }}
data:
  realm.yaml: |
    id: {{ .Values.iam.keycloak.configuration.realm.name }}
    realm: {{ .Values.iam.keycloak.configuration.realm.name }}
    displayName: {{ .Values.iam.keycloak.configuration.realm.displayName }}
    enabled: true
{{- if .Values.iam.keycloak.configuration.provider.createServiceAccount }}
    clients:
      - clientId: crossplane-keycloak-provider
        name: crossplane-keycloak-provider
        type:
        enabled: true
        clientAuthenticatorType: client-secret
        secret: $(env:client_secret)
        serviceAccountsEnabled: true
        #authorizationServicesEnabled: ...
        publicClient: false
        fullScopeAllowed: true
    users:
      - username: service-account-crossplane-keycloak-provider
        enabled: true
        totp: false
        serviceAccountClientId: "crossplane-keycloak-provider"
        realmRoles:
          - default-roles-{{ .Values.iam.keycloak.configuration.realm.name }}
        clientRoles:
          realm-management:
            - manage-users
            - manage-clients
            - manage-authorization
            - create-client
{{- end }}
{{- end }}