{{ if .Values.iam.keycloak.configuration.useKeycloakConfigCli -}}
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: eoepca-realm
  namespace: {{ .Release.Namespace }}
spec:
  keycloakCRName: {{ .Release.Name }}-keycloak-operator
  placeholders:
    client_secret:
      secret:
        name: keycloak-provider
        key: client_secret
  realm:
    id: {{ .Values.iam.keycloak.configuration.realm.name }}
    realm: {{ .Values.iam.keycloak.configuration.realm.name }}
    displayName: {{ .Values.iam.keycloak.configuration.realm.displayName }}
    enabled: true
{{- if .Values.iam.keycloak.configuration.provider.createServiceAccount }}
    clients:
      - clientId: crossplane-keycloak-provider
        name: crossplane-keycloak-provider
        type:
        enabled: true
        clientAuthenticatorType: client-secret
        secret: $(env:client_secret)
        serviceAccountsEnabled: true
        #authorizationServicesEnabled: ...
        publicClient: false
        fullScopeAllowed: true
    users:
      - username: service-account-crossplane-keycloak-provider
        enabled: true
        totp: false
        serviceAccountClientId: "crossplane-keycloak-provider"
        realmRoles:
          - default-roles-{{ .Values.iam.keycloak.configuration.realm.name }}
        clientRoles:
          realm-management:
            - manage-users
            - manage-clients
            - manage-authorization
            - create-client
{{- end }}
{{- end }}