{{ if .Values.iam.keycloak.configuration.useCrossplane -}}
{{ if .Values.iam.keycloak.configuration.provider.create -}}
apiVersion: keycloak.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: keycloak-provider-config
spec:
  credentials:
    source: Secret
    secretRef: {{- .Values.iam.keycloak.configuration.provider.secretRef | toYaml | nindent 6 }}
{{/*      name: keycloak-credentials*/}}
{{/*      key: credentials*/}}
{{/*      namespace: crossplane-system*/}}
{{- end }}
{{- end }}