{{ if .Values.iam.keycloak.enabled -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgresql
  namespace: {{ .Release.Namespace }}
{{- if and (not .Values.iam.opa.clientSecret) .Values.iam.keycloak.configuration.useSecretGenerator }}
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
{{- end }}
data:
  username: {{ "testuser" | b64enc | quote }}
  password: {{ "testpassword" | b64enc | quote }}
{{- end }}