{{ if .Values.iam.opa.enabled -}}
{{ if or .Values.iam.opa.createRoute .Values.iam.keycloak.configuration.createClients -}}
{{ if not .Values.iam.opa.clientSecretRef -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: opa-route
  namespace: {{ .Release.Namespace }}
{{- if and (not .Values.iam.opa.clientSecret) .Values.iam.keycloak.configuration.useSecretGenerator }}
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: client_secret
{{- end }}
data:
  client_id: {{ .Values.iam.opa.clientId | b64enc | quote }}
{{- if or .Values.iam.opa.clientSecret (not .Values.iam.keycloak.configuration.useSecretGenerator) }}
  client_secret: {{ .Values.iam.opa.clientSecret | default (randAlphaNum 32) | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}