{{ if .Values.iam.opa.enabled -}}
# Standard OPA service with fixed name; based on: https://www.openpolicyagent.org/docs/deployments#kubernetes
kind: Service
apiVersion: v1
metadata:
  name: iam-opa
  labels:
    app: iam-opa
spec:
  type: ClusterIP
  selector:
{{- if .Values.iam.opa.inline }}
    app.kubernetes.io/instance: {{ printf "%s" .Release.Name }}
    app.kubernetes.io/name: {{ printf "%s-opal-client" .Release.Name }}
    opal.ac/role: client
{{- else }}
    app: iam-opa
{{- end }}
  ports:
    - name: opa
      protocol: TCP
      port: 8181
      #targetPort: opa
{{- end }}