apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-postgresql
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgresql
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgresql
    spec:
      containers:
        - name: {{ .Release.Name }}-postgresql
          image: postgres:17
          volumeMounts:
            - mountPath: /data
              name: data
          env:
            - name: POSTGRES_USER
              #value: testuser
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: username
            - name: POSTGRES_PASSWORD
              #value: testpassword
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: password
            - name: PGDATA
              value: /data/pgdata
            - name: POSTGRES_DB
              value: keycloak
      #volumes:
      #  - name: cache-volume
      #    emptyDir: {}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi
        #storageClassName: managed-nfs-storage-retain
        volumeMode: Filesystem

