volumeClaim:
  name: eoepca-userman-pvc
  create: false
config:
  domain: test.185.52.193.87.nip.io
  volumeClaim:
    name: eoepca-userman-pvc
opendj:
  # This can be useful to workaround helm 'failed to upgrade' errors due to
  # immutable fields in the 'um-login-service-persistence-init-ss' job
  # persistence:
  #   enabled: false
  volumeClaim:
    name: eoepca-userman-pvc
oxauth:
  volumeClaim:
    name: eoepca-userman-pvc
oxtrust:
  volumeClaim:
    name: eoepca-userman-pvc
global:
  domain: test.185.52.193.87.nip.io
  nginxIp: 185.52.193.87
nginx:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - test.185.52.193.87.nip.io
    tls:
      - hosts:
          - test.185.52.193.87.nip.io
        secretName: login-service-tls
