{{ if .Values.sync.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "eoapi-maps-plugin.fullname" . }}-sync
  labels:
    {{- include "eoapi-maps-plugin.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.sync.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.sync.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.sync.failedJobsHistoryLimit }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.sync.backoffLimit }}
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: {{ .Values.restartPolicy | default "Never" }}
          containers:
            - name: {{ include "eoapi-maps-plugin.name" . }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: ["python3"]
              args:
                - "scripts/sync.py"
                - {{ .Values.sync.eoapiUrl | required ".Values.sync.eoapiUrl is required." }}
                - {{ .Values.sync.pygeoapiUrl | required ".Values.sync.pygeoapiUrl is required." }}
                {{- if .Values.sync.create }}
                - "-c"
                {{- end }}
                {{- if .Values.sync.delete }}
                - "-d"
                {{- end }}
                {{- if .Values.sync.update }}
                - "-u"
                {{- end }}
                {{- if .Values.sync.forceLinkMimetypeCheck }}
                - "-l"
                {{- end }}
              env:
                {{- range $key, $value := .Values.env }}
                - name: {{ $key }}
                value: {{ $value | quote }}
                {{- end }}
              {{- with .Values.volumeMounts }}
              volumeMounts:
                {{- toYaml . | nindent 16 }}
              {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumes }}
          volumes:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
