apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-portal.fullname" . }}
  labels:
    {{- include "django-portal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    name: http-portal
    targetPort: 8080
    protocol: TCP
  selector:
    app: portal