{{- $fullName := include "application-hub.fullname" . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-rbac
subjects:
  - kind: ServiceAccount
    name: {{ include "jupyterhub.hub-serviceaccount.fullname" (dict "Values" .Values.jupyterhub "Release" .Release "Chart" .Chart "Capabilities" .Capabilities) }}
    namespace: {{  .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
