{{- if and .Values.harvester.eodata.enabled .Values.harvester.eodata.createPVC }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.harvester.eodata.claimName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: eodata-storage
  annotations:
    helm.sh/resource-policy: keep
spec:
  {{- if .Values.harvester.eodata.reuseExistingVolume }}
  volumeName: {{ .Values.harvester.eodata.reuseExistingVolume }}
  {{- end }}
  accessModes:
    - {{ .Values.harvester.eodata.accessMode | default "ReadWriteMany" }}
  storageClassName: {{ .Values.harvester.eodata.storageClass | default "standard" }}
  resources:
    requests:
      storage: {{ .Values.harvester.eodata.size | default "100Gi" }}
{{- end }}
