apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.harvester.service.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.harvester.service.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.harvester.service.type }}
  ports:
    - port: {{ .Values.harvester.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.harvester.service.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
