apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.name" . }}-secret
data:
  POSTGRES_DB: "{{ .Values.configMap.postgresDb }}"
  POSTGRES_USER: "{{ .Values.configMap.postgresUser }}"
  POSTGRES_PASSWORD: "{{ .Values.configMap.postgresPassword }}"
  PGPASSWORD: "{{ .Values.configMap.pgPassword }}"