apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "knative-operator.fullname" . }}-knative-serving-operator-aggregated
  labels:
  {{- include "knative-operator.labels" . | nindent 4 }}
aggregationRule:
  clusterRoleSelectors:
  - matchExpressions:
    - key: serving.knative.dev/release
      operator: Exists
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "knative-operator.fullname" . }}-knative-serving-operator-aggregated-stable
  labels:
  {{- include "knative-operator.labels" . | nindent 4 }}
aggregationRule:
  clusterRoleSelectors:
  - matchExpressions:
    - key: app.kubernetes.io/name
      operator: In
      values:
      - knative-serving
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "knative-operator.fullname" . }}-knative-eventing-operator-aggregated
  labels:
  {{- include "knative-operator.labels" . | nindent 4 }}
aggregationRule:
  clusterRoleSelectors:
  - matchExpressions:
    - key: eventing.knative.dev/release
      operator: Exists
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "knative-operator.fullname" . }}-knative-eventing-operator-aggregated-stable
  labels:
  {{- include "knative-operator.labels" . | nindent 4 }}
aggregationRule:
  clusterRoleSelectors:
  - matchExpressions:
    - key: app.kubernetes.io/name
      operator: In
      values:
      - knative-eventing
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "knative-operator.fullname" . }}-knative-serving-operator
  labels:
  {{- include "knative-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - operator.knative.dev
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - system:auth-delegator
  resources:
  - clusterroles
  verbs:
  - bind
  - get
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - extension-apiserver-authentication-reader
  resources:
  - roles
  verbs:
  - bind
  - get
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - roles
  verbs:
  - create
  - delete
  - escalate
  - get
  - list
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - rolebindings
  verbs:
  - create
  - delete
  - list
  - get
  - update
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - caching.internal.knative.dev
  resources:
  - images
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - security.istio.io
  - apps
  - policy
  resources:
  - poddisruptionbudgets
  - peerauthentications
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - watch
  - update
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - create
  - delete
  - get
  - list
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - ""
  resourceNames:
  - knative-ingressgateway
  resources:
  - services
  - deployments
  - horizontalpodautoscalers
  verbs:
  - delete
- apiGroups:
  - ""
  resourceNames:
  - config-controller
  resources:
  - configmaps
  verbs:
  - delete
- apiGroups:
  - ""
  resourceNames:
  - knative-serving-operator
  resources:
  - serviceaccounts
  verbs:
  - delete
- apiGroups:
  - projectcontour.io
  resources:
  - httpproxies
  - tlscertificatedelegations
  verbs:
  - get
  - list
  - watch
  - update
  - create
  - delete
  - deletecollection
  - patch
- apiGroups:
  - guard.security.knative.dev
  resources:
  - guardians
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "knative-operator.fullname" . }}-knative-eventing-operator
  labels:
  {{- include "knative-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - operator.knative.dev
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - roles
  verbs:
  - create
  - delete
  - escalate
  - get
  - list
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - rolebindings
  verbs:
  - create
  - delete
  - list
  - get
  - update
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - caching.internal.knative.dev
  resources:
  - images
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - create
  - delete
  - get
  - list
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - update
  - get
  - list
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - update
  - get
  - list
  - watch
- apiGroups:
  - ""
  resourceNames:
  - knative-eventing-operator
  resources:
  - serviceaccounts
  verbs:
  - delete
- apiGroups:
  - rabbitmq.com
  resources:
  - rabbitmqclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - bindings
  - queues
  - exchanges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - bindings/status
  - queues/status
  - exchanges/status
  verbs:
  - get
- apiGroups:
  - keda.sh
  resources:
  - scaledobjects
  - scaledobjects/finalizers
  - scaledobjects/status
  - triggerauthentications
  - triggerauthentications/status
  verbs:
  - get
  - list
  - watch
  - update
  - create
  - delete
- apiGroups:
  - internal.kafka.eventing.knative.dev
  resources:
  - consumers
  - consumers/status
  - consumergroups
  - consumergroups/status
  verbs:
  - create
  - get
  - list
  - watch
  - patch
  - update
  - delete
- apiGroups:
  - internal.kafka.eventing.knative.dev
  resources:
  - consumers/finalizers
  - consumergroups/finalizers
  verbs:
  - update
  - delete
- apiGroups:
  - apps
  resources:
  - statefulsets/scale
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - watch
- apiGroups:
  - '*'
  resources:
  - configmaps
  verbs:
  - delete
- apiGroups:
  - '*'
  resources:
  - configmaps
  - services
  verbs:
  - get
  - list
  - watch
  - update
  - create
  - delete
- apiGroups:
  - '*'
  resources:
  - pods
  verbs:
  - list
  - update
  - get
  - watch
- apiGroups:
  - '*'
  resources:
  - pods/finalizers
  verbs:
  - get
  - list
  - create
  - update
  - delete
- apiGroups:
  - '*'
  resources:
  - events
  verbs:
  - patch
  - create
- apiGroups:
  - '*'
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - update
  - create
  - delete
- apiGroups:
  - '*'
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
  - update
  - create
  - delete
- apiGroups:
  - '*'
  resourceNames:
  - kafka-channel-config
  resources:
  - configmaps
  verbs:
  - patch
- apiGroups:
  - '*'
  resourceNames:
  - kafka-webhook
  resources:
  - horizontalpodautoscalers
  verbs:
  - delete
- apiGroups:
  - '*'
  resources:
  - leases
  verbs:
  - delete
- apiGroups:
  - '*'
  resourceNames:
  - kafka-webhook
  resources:
  - poddisruptionbudgets
  verbs:
  - delete
- apiGroups:
  - '*'
  resources:
  - services
  verbs:
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - deletecollection
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  - issuers
  - clusterissuers
  verbs:
  - create
  - delete
  - update
  - list
  - get
  - watch
- apiGroups:
  - trust.cert-manager.io
  resources:
  - bundles
  verbs:
  - create
  - delete
  - update
  - list
  - get
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "knative-operator.fullname" . }}-knative-operator-webhook
  labels:
  {{- include "knative-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - create
  - update
  - list
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces/finalizers
  verbs:
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch