apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "knative-operator.fullname" . }}-knative-serving-operator
  labels:
  {{- include "knative-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "knative-operator.fullname" . }}-knative-serving-operator'
subjects:
- kind: ServiceAccount
  name: '{{ include "knative-operator.fullname" . }}-knative-operator'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "knative-operator.fullname" . }}-knative-eventing-operator
  labels:
  {{- include "knative-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "knative-operator.fullname" . }}-knative-eventing-operator'
subjects:
- kind: ServiceAccount
  name: '{{ include "knative-operator.fullname" . }}-knative-operator'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "knative-operator.fullname" . }}-operator-webhook
  labels:
  {{- include "knative-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "knative-operator.fullname" . }}-knative-operator-webhook'
subjects:
- kind: ServiceAccount
  name: '{{ include "knative-operator.fullname" . }}-operator-webhook'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "knative-operator.fullname" . }}-knative-serving-operator-aggregated
  labels:
  {{- include "knative-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "knative-operator.fullname" . }}-knative-serving-operator-aggregated'
subjects:
- kind: ServiceAccount
  name: '{{ include "knative-operator.fullname" . }}-knative-operator'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "knative-operator.fullname" . }}-knative-serving-operator-aggregated-stable
  labels:
  {{- include "knative-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "knative-operator.fullname" . }}-knative-serving-operator-aggregated-stable'
subjects:
- kind: ServiceAccount
  name: '{{ include "knative-operator.fullname" . }}-knative-operator'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "knative-operator.fullname" . }}-knative-eventing-operator-aggregated
  labels:
  {{- include "knative-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "knative-operator.fullname" . }}-knative-eventing-operator-aggregated'
subjects:
- kind: ServiceAccount
  name: '{{ include "knative-operator.fullname" . }}-knative-operator'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "knative-operator.fullname" . }}-knative-eventing-operator-aggregated-stable
  labels:
  {{- include "knative-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "knative-operator.fullname" . }}-knative-eventing-operator-aggregated-stable'
subjects:
- kind: ServiceAccount
  name: '{{ include "knative-operator.fullname" . }}-knative-operator'
  namespace: '{{ .Release.Namespace }}'