# Default values for iam-bb-config.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Note: The following configuration is a subset of the iam-bb values.yaml
# file.
# Hence instead of adapting this values.yaml file, you may also reuse the
# values.yaml file that was used to install the IAM BB through the iam-bb
# Helm chart.

iam:
  keycloak:
    # Optional configuration to apply as Crossplane CRs.
    # Evaluated by the iam-bb-config Helm chart.
    # See also section keycloak.keycloakConfigCli for another way to
    # configure Keycloak, which can be combined with this approach.
    # By default, the EOEPCA realm and a user account for Crossplane
    # should be initialized using keycloak-config-cli, whereas further
    # configuration (like clients, groups etc.) should be applied via
    # the Crossplane Keycloak Provider.
    configuration:
      # Set this to true to enable generation of Crossplane CRs;
      # if set to false, Crossplane is not used and no CRs are generated.
      useCrossplane: true
      # Set to true to auto-generate clients as Crossplane CRs.
      createClients: false
      realm:
        # Set to true to auto-generate realm as Crossplane CR.
        create: false
        # Name of realm to create or of existing realm to create clients in
        name: eoepca
        displayName: EOEPCA
        # TODO: Maybe add spec or forProvider section here and reference it from template
      provider:
        # Set to true to generate Provider config for Keycloak
        create: false
        # Set to true to create a client with service account to be used by Crossplane
        # Keycloak Provider.
        createServiceAccount: false
        # Client secret for the Crossplane Keycloak Provider client.
        # Unfortunately it is currently not possible to generate this secret via
        # kubernetes-secret-generator. Therefore it must either be specified here
        # or provided through an existing secret.
        clientSecret: ""
        # Reference to existing secret containing Keycloak location and credentials
        secretRef:
          name: "" #keycloak-credentials
          key: "" #credentials
          namespace: "" #crossplane-system
  opa:
    enabled: false
  identityApi:
    enabled: false
