# Default values for iam-bb-config.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Note: The following configuration is a subset of the iam-bb values.yaml
# file.
# Hence instead of adapting this values.yaml file, you may also reuse the
# values.yaml file that was used to install the IAM BB through the iam-bb
# Helm chart.

iam:
  keycloak:
    configuration:
      # Set this to true to enable generation of Crossplane CRs;
      # if set to false, Crossplane is not used and no CRs are generated.
      useCrossplane: true
      # Set to true to auto-generate clients as Crossplane CRs.
      createClients: false
      realm:
        # Set to true to auto-generate realm as Crossplane CR.
        create: false
        # Name of realm to create or of existing realm to create clients in
        name: eoepca
        displayName: EOEPCA
        # TODO: Maybe add spec or forProvider section here and reference it from template
      provider:
        # Set to true to generate Provider config for Keycloak
        create: false
        # Reference to existing secret containing Keycloak location and credentials
        secretRef:
          name: keycloak-credentials
          key: credentials
          namespace: crossplane-system
  opa:
    enabled: false
  identityApi:
    enabled: false
