replicaCount: 1

image:
  repository: ghcr.io/eoepca/eoapi-maps-plugin
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

env: []

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

config: {}

sync:
  enabled: false
  schedule: "*/10 * * * *" # every 10 minutes
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  eoapiUrl: ""
  pygeoapiUrl: ""
  create: true
  update: true
  delete: true
  forceLinkMimetypeCheck: false
  backoffLimit: 1
