imagePullSecrets: []

harvester:
  service:
    name: registration-harvester
    type: ClusterIP
    port: 8080
  image:
    repository: eoepca/registration-harvester
    pullPolicy: Always
    tag: 2.0.0-rc2
  secret:
    name: ""
  volume_name: registration-harvester-config
  volume_path: /worker/config
  container_port: 8080
  config:
    worker:
      log_level: INFO
      flowable:
        host: https://registration-harvester-api.develop.eoepca.org/flowable-rest
        tls: "true"
        cacert: ""
      topics:
      handlers:
  eodata:
    enabled: false
    createPVC: true
    # reuseExistingVolume: existing-pv-name  # optional override
    claimName: eodata
    volumeName: eodata
    mountPath: /eodata
    accessMode: ReadWriteMany
    storageClass: standard
    size: 100Gi
