imagePullSecrets: []

harvester:
  service:
    name: registration-harvester
    type: ClusterIP
    port: 8080
  image:
    repository: eoepca/registration-harvester
    pullPolicy: Always
    tag: main
  secret:
    name: ""
  volume_name: registration-harvester-config
  volume_path: /worker/config
  container_port: 8080
  config:
    worker:
      log_level: INFO
      flowable:
        host: https://registration-harvester-api.develop.eoepca.org/flowable-rest
        tls: "true"
        cacert: ""
      topics:
      handlers:
