apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "identity-api.name" . }}
  labels:
    {{- include "identity-api.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    IDENTITY_ADMIN_PASSWORD: "{{ .Values.secrets.identityAdminPassword }}"