apiVersion: v1
kind: Secret
metadata:
  name: {{ include "identity-gatekeeper.fullname" . }}
  labels:
    {{- include "identity-gatekeeper.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  gatekeeper-config.yaml: |
    {{- tpl (.Values.config | toYaml) $ | nindent 4 }}