{{ if .Values.iam.keycloak.configuration.useCrossplane -}}
{{ if .Values.iam.keycloak.configuration.createClients -}}
{{ if .Values.iam.opa.enabled -}}
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: {{ printf "%s-opa-client" .Release.Name }}
spec:
  deletionPolicy: Delete
  forProvider:
    accessType: confidential
    clientId: opa
    clientSecretSecretRef:
      key: client_secret
      name: opa-route
      namespace: {{ .Release.Namespace }}
    realmId: {{ .Values.iam.keycloak.configuration.realm.name }}
    serviceAccountsEnabled: true
    name: opa
{{- if .Values.iam.opa.url }}
    rootUrl: {{ .Values.iam.opa.url }}
    adminUrl: {{ .Values.iam.opa.url }}
{{- end }}
    #baseUrl: TBD
    validRedirectUris:
      - "/*" # TODO: Maybe make more specific
{{/*{{- if .Values.iam.opa.url }}*/}}
{{/*      - {{ .Values.iam.opa.url }}/.apisix/redirect*/}}
{{/*{{- end }}*/}}
    webOrigins:
      - "/*"
  providerConfigRef:
    name: {{ printf "%s-keycloak-provider-config" .Release.Name }}
{{- end }}
{{- end }}
{{- end }}