{{ if .Values.iam.keycloak.configuration.useCrossplane -}}
{{ if .Values.iam.keycloak.configuration.createClients -}}
{{ if .Values.iam.identityApi.enabled -}}
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: {{ printf "%s-identity-api-client" .Release.Name }}
spec:
  deletionPolicy: Delete
  forProvider:
    accessType: confidential
    clientId: identity-api
    clientSecretSecretRef:
      key: client_secret
      name: identity-api-route
      namespace: {{ .Release.Namespace }}
    realmId: {{ .Values.iam.keycloak.configuration.realm.name }}
    serviceAccountsEnabled: true
    standardFlowEnabled: true
    useRefreshTokens: true
    name: identity-api
{{- if .Values.iam.identityApi.url }}
    rootUrl: {{ .Values.iam.identityApi.url }}
    adminUrl: {{ .Values.iam.identityApi.url }}
{{- end }}
    validRedirectUris:
      - "/*"
    webOrigins:
      - "/*"
  providerConfigRef:
    name: {{ printf "%s-keycloak-provider-config" .Release.Name }}
{{- end }}
{{- end }}
{{- end }}