{{ if .Values.iam.keycloak.configuration.useCrossplane -}}
{{ if .Values.iam.keycloak.configuration.createClients -}}
{{ if .Values.iam.opa.enabled -}}
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: {{ printf "%s-opa-client" .Release.Name }}
spec:
  deletionPolicy: Delete
  forProvider:
    accessType: confidential
    clientId: opa
    clientSecretSecretRef:
      key: client_secret
      name: opa-route
      namespace: {{ .Release.Namespace }}
    realmId: {{ .Values.iam.keycloak.configuration.realm.name }}
    serviceAccountsEnabled: true
  providerConfigRef:
    name: {{ printf "%s-keycloak-provider-config" .Release.Name }}
{{- end }}
{{- end }}
{{- end }}