{{- if .Values.knativeServing.install }}
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: {{ .Values.knativeServing.namespace }}
spec:
  config:
    domain:
      {{ .Values.knativeServing.domain }}: ""
    network:
      ingress-class: kourier.ingress.networking.knative.dev
  ingress:
    kourier:
      enabled: true
  version: {{ .Values.knativeServing.version }}
{{- end }}
