{{- if .Values.eventing.install }}
{{- $knativeEventingCRD := lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "" "knativeeventings.operator.knative.dev" }}
{{- if not $knativeEventingCRD }}
{{- fail "KnativeEventing CRD not found. Please install Knative Operator first." }}
{{- end }}
{{- end }}

{{- if .Values.serving.install }}
{{- $knativeServingCRD := lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "" "knativeservings.operator.knative.dev" }}
{{- if not $knativeServingCRD }}
{{- fail "KnativeServing CRD not found. Please install Knative Operator first." }}
{{- end }}
{{- end }}
