name: Publish Charts

on:
  push:
    branches:
      - main
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Copycat
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.PUSH_TOKEN }}
        src_path: /charts/.
        dst_path: /charts/
        clean: true
        dst_owner: EOEPCA
        dst_repo_name: helm-charts
        dst_branch: test-delete
        src_branch: main
        commit_message: Commit triggered by a change on the main branch of helm-charts-dev

