name: Publish Charts

on:
  push:
    branches:
      - main
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Copycat
      uses: andstor/copycat-action@v3
      with:
        personal_token: "${{ secrets.GITHUB_TOKEN }}"
        src_path: /charts
        dst_path: /charts
        dst_owner: EOEPCA
        dst_repo_name: helm-charts
        dst_branch: test
        src_branch: main
        username: "$GITHUB_ACTOR"
        email: "$GITHUB_ACTOR@users.noreply.github.com"

