name: Publish Charts

on:
  push:
    branches:
      - main
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Copycat
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.PUSH_TOKEN }}
        src_path: /charts
        dst_path: /
        dst_owner: EOEPCA
        dst_repo_name: helm-charts
        dst_branch: test
        src_branch: main
        commit_message: Commit triggered by "$GITHUB_SHA" on helm-charts-dev

